# see http://docs.travis-ci.com/user/languages/csharp/

language: csharp

solution: src/mono/WampSharpMono.sln

install:
  - travis_retry mono src/mono/.nuget/NuGet.exe restore src/mono/WampSharpMono.sln
  - travis_retry mono src/mono/.nuget/NuGet.exe install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release src/mono/WampSharpMono.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/mono/Tests/WampSharp.Tests/bin/Release/WampSharp.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/mono/Tests/WampSharp.Tests.Wampv2/bin/Release/WampSharp.Tests.Wampv2.dll

branches:
 except:
  - wampv1
